config/routes.rb
DeborahcProj2::Application.routes.draw do
  root :to => "notes#landing"

  get "sessions/login" => "sessions#new", :as => "log_in"
  get "users/new"
  get "notes/landing" => "notes#landing", :as => "notes_landing"
  get "sessions/logout" => "sessions#destroy", :as => "log_out"
  get "users/signup" => "users#new", :as => "sign_up"

  resources :notes
  resources :users
  resources :sessions

  unless Rails.application.config.consider_all_requests_local
    get '/404' =>'errors#not_found'
  end

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DeborahcProj2</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="user_nav">
  <% if current_user %>
  Logged in as <%= current_user.email %>.
  <%= link_to "Log out", log_out_path %>
  <% else %>
  <%= link_to "Sign up", sign_up_path %> or
  <%= link_to "log in", log_in_path %>
  <% end %>

     <% flash.each do |name, msg| %>
   <%= content_tag :div, msg, :id => "flash_#{name}" %>
  <% end %> 
</div>
<!-- The navigation bar present at the top of each page -->
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="brand"  <%= link_to "TeamNote", notes_landing_path %>

      </a>
    </div>
  </div>
</div>
<!-- Login and logout buttons -->

<div class="container">
 <%= yield %>
</div>
</body>
</html>